# Generated by Django 5.1.6 on 2025-03-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20),
        ),
    ]
